default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: so_say_me_development

test:
  <<: *default
  database: so_say_me_test

production:
  <<: *default
  database: so_say_me_production
  username: so_say_me
  password: <%= ENV['SO_SAY_ME_DATABASE_PASSWORD'] %>